version: '3.9'

services:
  #springboot:
  #  container_name: SpringBoot

  postgres:
    container_name: Postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: traffico
    ports:
      - "5432:5432"
